[package]
name = "captest"
version = "0.1.0"
edition = "2024"

[dependencies]
scap = "0.1.0-beta.1"
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
tokio = { version = "1.0", features = ["full"] }
